### ISSUE TITLE
MLX-LM 模型微调实践

### ISSUE THREAD

**Issue by jincdream** [jincdream/jincdream.github.io#21]
# MLX-LM 模型微调与生成技术文档

## 模型加载与初始化

MLX-LM框架提供了便捷的模型加载接口。以下是基本的模型加载流程：

```python
from mlx_lm import load, generate

# 加载模型和分词器
model, tokenizer = load(
    "./models/模型名称",
    tokenizer_config={"eos_token": "<|endoftext|>"},
    adapter_path='./lora/模型适配器路径/'
)
```

### 基础生成方法

MLX-LM支持多种生成参数配置：

```python
response = generate(
    model, 
    tokenizer, 
    prompt=text,
    verbose=True,      # 是否显示生成过程
    temp=0.4,         # 温度参数，控制随机性
    top_p=0.8,        # 核采样参数
    repetition_penalty=1.05,  # 重复惩罚系数
    max_tokens=8000   # 最大生成长度
)
```

### 带超时控制的生成

为了防止生成过程卡死，可以实现带超时控制的生成机制：

```python
import signal
from mlx_lm import generate

# 设置信号处理器，用于处理超时情况
signal.signal(signal.SIGALRM, timeout_handler)

# 设置定时器，timeout秒后将触发SIGALRM信号
signal.alarm(timeout)

try:
    # 构建标准的对话消息格式
    messages = [
        # system消息用于设置AI助手的角色和行为
        {"role": "system", "content": system},
        # user消息包含用户的实际输入
        {"role": "user", "content": prompt}
    ]
    
    # 使用tokenizer将消息转换为模型可理解的格式
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,      # 不进行分词，返回文本字符串
        add_generation_prompt=True  # 添加生成提示符
    )
    
    # 调用模型生成回复
    # verbose=True 表示显示生成过程
    return generate(model, tokenizer, prompt=text, verbose=True)
    
except TimeoutException:
    # 当生成时间超过timeout秒时，捕获超时异常并打印提示
    print(f"生成超时: {timeout}秒")
    
finally:
    # 无论是否发生异常，都确保清除定时器
    # 防止定时器影响后续的代码执行
    signal.alarm(0)
```

### JSONL格式数据处理

训练数据需要准备成JSONL格式，每行包含一个JSON对象：

```python
{
    "messages": [
        {"role": "user", "content": "用户输入"},
        {"role": "assistant", "content": "助手回复"}
    ]
}
```

参考代码：

```python
import json
import gen
# 打开输入文件和输出文件
with open('./TrainData/train.jsonl', 'r', encoding='utf-8') as infile, open('./output_readed.jsonl', 'w', encoding='utf-8') as outfile:
    # 逐行读取输入文件
    for line in infile:
        # 将JSON字符串转换为字典
        data = json.loads(line)
        print(data['messages'])
        d = gen.generate_with_timeout(f"你是前端开发专家，擅长使用xxx组件库、vue3、typescript来帮助解决代码问题。将下面代码语料内容，处理问为正常的问答对，然后原样输出。",300)
        # gen.generate_with_timeout()
        # 对数据进行修改，这里以添加一个新键值对为例
        data['messages'] = d
        
        # 将修改后的字典转换回JSON字符串，并写入输出文件
        json_line = json.dumps(data, ensure_ascii=False)
        outfile.write(json_line + '\n')

print("处理完成，修改后的数据已保存到output.jsonl文件中。")
```

### 代码语料处理

对于代码相关的训练数据，可以进行特殊处理：

```python
def process_ts_file(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        code = file.read().strip()
        prompt2 = f"你是资深的前端开发专家，精通typescript，拥有丰富的前端开发经验，你将帮助用户阅读并理解【代码】，根据【代码】的内容，分析这个【代码】是如何一步步实现，然后输出【实现过程】。\n\n【代码】\n{code}\n\n【实现过程】\n要求先分析出具体的产品逻辑，最后描述实现的具体逻辑\n\nAssistan:\n"
        suma = generate_with_timeout(model, tokenizer, prompt2, 300)
        return {
            "messages": [
                {"role": "user", "content": suma},
                {"role": "assistant", "content": code}
            ]
        }
```

## 注意事项

1. **模型配置**：
   - 确保正确设置tokenizer_config
   - 选择合适的eos_token
   - 根据实际需求调整生成参数

2. **内存管理**：
   - 对于大模型，注意控制batch_size
   - 合理设置max_tokens避免内存溢出

3. **性能优化**：
   - 使用timeout机制防止生成卡死
   - 适当调整temperature和top_p参数平衡生成质量和速度

4. **数据处理**：
   - 确保训练数据格式规范
   - 对特殊字符进行适当处理
   - 控制单条数据的长度

## 实践建议

1. **生成参数调优**：
   - temperature建议范围：0.3-0.8
   - top_p建议范围：0.8-0.95
   - repetition_penalty建议范围：1.0-1.2

2. **超时控制**：
   - 根据任务复杂度设置合理的超时时间
   - 对不同类型的生成任务设置不同的超时阈值

3. **数据预处理**：
   - 对代码进行规范化处理
   - 移除无关的注释和空行
   - 统一编码格式

4. **错误处理**：
   - 实现完善的异常捕获机制
   - 记录生成过程中的错误信息
   - 提供优雅的降级方案

### 基础配置参数

MLX-LM支持通过YAML配置文件进行微调参数设置：

```yaml
# 模型路径配置
model: "./models/模型名称"  # 本地模型目录或Hugging Face仓库路径
adapter_path: "./lora/适配器路径"  # 保存训练后的适配器权重路径

# 训练基础参数
train: true                # 是否进行训练
batch_size: 2             # 批次大小
iters: 10000              # 训练迭代次数
learning_rate: 1e-5       # Adam学习率
max_seq_length: 10000     # 最大序列长度
```

### LoRA参数配置

```yaml
# LoRA相关参数
lora_layers: 48           # 需要微调的层数
lora_parameters:
  keys: ["self_attn.q_proj", "self_attn.v_proj"]  # 应用LoRA的层键
  rank: 8                 # LoRA秩
  scale: 20.0            # 缩放因子
  dropout: 0.0           # Dropout率
```

### 训练控制参数

```yaml
# 训练过程控制
steps_per_report: 10      # 损失报告间隔步数
steps_per_eval: 200       # 验证间隔步数
save_every: 200           # 模型保存间隔步数
grad_checkpoint: false    # 是否使用梯度检查点

# 验证与测试
val_batches: 10          # 验证批次数，-1使用整个验证集
test: false              # 训练后是否在测试集上评估
test_batches: 100        # 测试批次数，-1使用整个测试集
```

### 学习率调度

支持配置学习率调度策略：

```yaml
lr_schedule:
  name: cosine_decay      # 余弦衰减调度
  warmup: 100            # 预热步数，0表示无预热
  warmup_init: 1e-7      # 预热初始学习率
  arguments: [1e-5, 1000, 1e-7]  # 调度器参数
```

### 数据集配置

支持直接使用Hugging Face数据集：

```yaml
hf_dataset:
  name: "数据集名称"
  train_split: "train[:1000]"    # 训练集切片
  valid_split: "train[-100:]"    # 验证集切片
  prompt_feature: "text"         # 提示特征名
  completion_feature: "summary"  # 完成特征名
```

## 微调最佳实践

1. **LoRA配置建议**：
   - `lora_layers`: 根据模型大小选择，通常为16-48
   - `rank`: 8-16之间，权衡效果和训练成本
   - `scale`: 推荐范围10.0-30.0

2. **训练参数建议**：
   - `batch_size`: 根据显存大小调整，通常2-8
   - `learning_rate`: 1e-4到1e-6之间
   - `max_seq_length`: 根据任务需求设置，注意显存占用

3. **调度策略选择**：
   - 对于较长训练周期，建议使用余弦衰减
   - 预热步数建议设置为总步数的1%-5%

4. **验证与保存**：
   - `steps_per_eval`: 建议200-500步验证一次
   - `save_every`: 根据总训练步数确定，通常与验证步数相同

### 训练脚本示例

```bash:scripts/train.sh
#!/bin/bash

# 设置环境变量
export HF_HOME="./cache"
export HF_DATASETS_CACHE="./cache"

# 执行训练
mlx_lm.lora \
    --config ./config.yaml \
    --train \
    --iters 10000 \
    --batch-size 2 \
    --learning-rate 1e-5 \
    --steps-per-report 10 \
    --steps-per-eval 200 \
    --save-every 200 \
    --val-batches 10
```

### LoRA推理脚本示例

```bash:scripts/generate.sh
#!/bin/bash

# 单次对话生成
mlx_lm.generate \
    --model ./models/base-model/ \
    --adapter-path ./lora/checkpoint/ \
    --prompt "请输入你的问题" \
    --max-tokens 2048 \
    --temp 0.7 \
    --top-p 0.9

# 批量对话生成
mlx_lm.generate \
    --model ./models/base-model/ \
    --adapter-path ./lora/checkpoint/ \
    --prompt-file ./prompts.txt \
    --max-tokens 2048 \
    --temp 0.7 \
    --top-p 0.9 \
    --output-file ./responses.txt
```

### Python API调用示例

```python:scripts/inference.py
from mlx_lm import load, generate

def load_model_with_lora():
    # 加载基础模型和LoRA权重
    model, tokenizer = load(
        "./models/base-model/",
        adapter_path="./lora/checkpoint/",
        tokenizer_config={"eos_token": "<|endoftext|>"}
    )
    return model, tokenizer

def batch_generate(model, tokenizer, prompts):
    responses = []
    for prompt in prompts:
        response = generate(
            model,
            tokenizer,
            prompt=prompt,
            max_tokens=2048,
            temp=0.7,
            top_p=0.9,
            repetition_penalty=1.1
        )
        responses.append(response)
    return responses

# 使用示例
if __name__ == "__main__":
    model, tokenizer = load_model_with_lora()
    prompts = [
        "第一个问题",
        "第二个问题",
        "第三个问题"
    ]
    responses = batch_generate(model, tokenizer, prompts)
    for prompt, response in zip(prompts, responses):
        print(f"问题: {prompt}")
        print(f"回答: {response}\n")
```
